/* eslint-disable */
// Generated by tauri-specta. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	isReady: () => __TAURI_INVOKE<boolean>("is_ready"),
	startupStatus: () => __TAURI_INVOKE<StartupStatus>("startup_status"),
	mobileSystemInfo: () => typedError<{
	deviceName: string,
	safeArea: SafeAreaInsets,
} | null, CommandError>(__TAURI_INVOKE("mobile_system_info")),
	setSystemBarsStyle: (darkBackground: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("set_system_bars_style", { darkBackground })),
	syncStatus: () => __TAURI_INVOKE<SyncStatus>("sync_status"),
	loadSettings: () => typedError<SettingsSnapshot, CommandError>(__TAURI_INVOKE("load_settings")),
	saveSettings: (update: SettingsUpdate) => typedError<SettingsSnapshot, CommandError>(__TAURI_INVOKE("save_settings", { update })),
	restartApp: () => __TAURI_INVOKE<void>("restart_app"),
	historyStatus: () => typedError<[number, number], CommandError>(__TAURI_INVOKE("history_status")),
	undo: () => typedError<boolean, CommandError>(__TAURI_INVOKE("undo")),
	redo: () => typedError<boolean, CommandError>(__TAURI_INVOKE("redo")),
	createNode: (kind: NodeKind, title: string | null, content: string, contentJson: string | null) => typedError<Node, CommandError>(__TAURI_INVOKE("create_node", { kind, title, content, contentJson })),
	updateNode: (id: number, title: string | null, content: string, contentJson: string | null) => typedError<null, CommandError>(__TAURI_INVOKE("update_node", { id, title, content, contentJson })),
	renamePage: (uuid: string, title: string | null) => typedError<Node, CommandError>(__TAURI_INVOKE("rename_page", { uuid, title })),
	createNote: () => typedError<CreatedNote, CommandError>(__TAURI_INVOKE("create_note")),
	setBlockContent: (uuid: string, block: BlockContent) => typedError<[Node, number], CommandError>(__TAURI_INVOKE("set_block_content", { uuid, block })),
	splitBlock: (id: number, parts: BlockContent[]) => typedError<Node[], CommandError>(__TAURI_INVOKE("split_block", { id, parts })),
	linkNodes: (src: number, dst: number, kind: string, weight: number | null) => typedError<null, CommandError>(__TAURI_INVOKE("link_nodes", { src, dst, kind, weight })),
	getNode: (id: number) => typedError<{
	id: number,
	uuid: string,
	kind: NodeKind,
	title: string | null,
	content: string,
	content_json: string | null,
	parent_id: number | null,
	position: number | null,
	created_at: number,
	updated_at: number,
} | null, CommandError>(__TAURI_INVOKE("get_node", { id })),
	getContainingPage: (id: number) => typedError<{
	id: number,
	uuid: string,
	kind: NodeKind,
	title: string | null,
	content: string,
	content_json: string | null,
	parent_id: number | null,
	position: number | null,
	created_at: number,
	updated_at: number,
} | null, CommandError>(__TAURI_INVOKE("get_containing_page", { id })),
	neighbors: (id: number, depth: number) => typedError<Node[], CommandError>(__TAURI_INVOKE("neighbors", { id, depth })),
	searchFts: (query: string, limit: number) => typedError<SearchHit[], CommandError>(__TAURI_INVOKE("search_fts", { query, limit })),
	searchVec: (query: string, limit: number) => typedError<SearchHit[], CommandError>(__TAURI_INVOKE("search_vec", { query, limit })),
	searchHybrid: (query: string, limit: number) => typedError<SearchHit[], CommandError>(__TAURI_INVOKE("search_hybrid", { query, limit })),
	/**  Retrieve via hybrid RRF, then rerank with the configured provider. */
	searchAgentic: (query: string, limit: number) => typedError<SearchHit[], CommandError>(__TAURI_INVOKE("search_agentic", { query, limit })),
	chatStream: (history: ChatTurn[], message: string, allowWrites: boolean, activeNodeUuid: string | null, requestId: string, onEvent: Channel<ChatEvent>) => typedError<string, CommandError>(__TAURI_INVOKE("chat_stream", { history, message, allowWrites, activeNodeUuid, requestId, onEvent })),
	cancelChat: (requestId: string) => __TAURI_INVOKE<boolean>("cancel_chat", { requestId }),
	listEntities: (limit: number | null) => typedError<Node[], CommandError>(__TAURI_INVOKE("list_entities", { limit })),
	listPages: (limit: number | null) => typedError<Node[], CommandError>(__TAURI_INVOKE("list_pages", { limit })),
	deletePage: (id: number) => typedError<boolean, CommandError>(__TAURI_INVOKE("delete_page", { id })),
	findBacklinks: (id: number, kind: string | null) => typedError<Node[], CommandError>(__TAURI_INVOKE("find_backlinks", { id, kind })),
	graphSnapshot: (focusId: number | null) => typedError<GraphSnapshot, CommandError>(__TAURI_INVOKE("graph_snapshot", { focusId })),
	exportData: () => typedError<string | null, CommandError>(__TAURI_INVOKE("export_data")),
	importData: () => typedError<string | null, CommandError>(__TAURI_INVOKE("import_data")),
	createBackup: () => typedError<string, CommandError>(__TAURI_INVOKE("create_backup")),
	chooseSyncDirectory: () => typedError<string | null, CommandError>(__TAURI_INVOKE("choose_sync_directory")),
	syncPush: () => typedError<string, CommandError>(__TAURI_INVOKE("sync_push")),
	syncPull: () => typedError<string, CommandError>(__TAURI_INVOKE("sync_pull")),
	attachFile: (parentId: number) => typedError<{
	id: number,
	uuid: string,
	kind: NodeKind,
	title: string | null,
	content: string,
	content_json: string | null,
	parent_id: number | null,
	position: number | null,
	created_at: number,
	updated_at: number,
} | null, CommandError>(__TAURI_INVOKE("attach_file", { parentId })),
	listAttachments: (parentId: number) => typedError<Node[], CommandError>(__TAURI_INVOKE("list_attachments", { parentId })),
	openAttachment: (id: number) => typedError<null, CommandError>(__TAURI_INVOKE("open_attachment", { id })),
	deleteAttachment: (id: number) => typedError<boolean, CommandError>(__TAURI_INVOKE("delete_attachment", { id })),
	createPage: (title: string) => typedError<Node, CommandError>(__TAURI_INVOKE("create_page", { title })),
	listBlockChildren: (parentId: number) => typedError<Node[], CommandError>(__TAURI_INVOKE("list_block_children", { parentId })),
	createBlock: (parentId: number | null, position: number | null, content: string, contentJson: string | null) => typedError<Node, CommandError>(__TAURI_INVOKE("create_block", { parentId, position, content, contentJson })),
	indentBlock: (uuid: string) => typedError<Node, CommandError>(__TAURI_INVOKE("indent_block", { uuid })),
	outdentBlock: (uuid: string) => typedError<Node, CommandError>(__TAURI_INVOKE("outdent_block", { uuid })),
	moveBlockUp: (uuid: string) => typedError<Node, CommandError>(__TAURI_INVOKE("move_block_up", { uuid })),
	moveBlockDown: (uuid: string) => typedError<Node, CommandError>(__TAURI_INVOKE("move_block_down", { uuid })),
	deleteBlock: (id: number) => typedError<boolean, CommandError>(__TAURI_INVOKE("delete_block", { id })),
	replaceBlockRefs: (blockId: number, wikilinkTitles: string[], blockUuids: string[]) => typedError<number, CommandError>(__TAURI_INVOKE("replace_block_refs", { blockId, wikilinkTitles, blockUuids })),
	getOrCreatePageByTitle: (title: string) => typedError<Node, CommandError>(__TAURI_INVOKE("get_or_create_page_by_title", { title })),
	getPageByTitle: (title: string) => typedError<{
	id: number,
	uuid: string,
	kind: NodeKind,
	title: string | null,
	content: string,
	content_json: string | null,
	parent_id: number | null,
	position: number | null,
	created_at: number,
	updated_at: number,
} | null, CommandError>(__TAURI_INVOKE("get_page_by_title", { title })),
	getNodeByUuid: (uuid: string) => typedError<{
	id: number,
	uuid: string,
	kind: NodeKind,
	title: string | null,
	content: string,
	content_json: string | null,
	parent_id: number | null,
	position: number | null,
	created_at: number,
	updated_at: number,
} | null, CommandError>(__TAURI_INVOKE("get_node_by_uuid", { uuid })),
	searchPagesByTitle: (query: string, limit: number) => typedError<Node[], CommandError>(__TAURI_INVOKE("search_pages_by_title", { query, limit })),
	searchBlocksFts: (query: string, limit: number) => typedError<Node[], CommandError>(__TAURI_INVOKE("search_blocks_fts", { query, limit })),
};

/** Events */
export const events = {
	domainEvent: makeEvent<DomainEventMessage>("domain:event"),
};

/* Types */
export type BlockContent = {
	content: string,
	wikilinkTitles: string[],
	blockUuids: string[],
};

export type ChatEvent = { kind: "text_delta"; text: string } | { kind: "reasoning"; text: string } | { kind: "tool_start"; id: string; name: string; args: unknown } | { kind: "tool_end"; id: string; result: string } | { kind: "done"; text: string } | { kind: "error"; message: string } | { kind: "usage"; inputTokens: number; outputTokens: number; totalTokens: number } | { kind: "cancelled" };

export type ChatTurn = { role: "user"; text: string } | { role: "assistant"; text: string };

export type CommandError = {
	code: CommandErrorCode,
	message: string,
};

export type CommandErrorCode = "invalid_input" | "not_found" | "conflict" | "unavailable" | "internal";

export type CreatedNote = {
	page: Node,
	initialBlock: Node,
};

/**
 *  The single frontend invalidation stream for persisted Rust state.
 *  Payloads carry affected IDs when a command can identify them; whole-workspace
 *  replacements (import/sync) deliberately request a full cache refresh.
 */
export type DomainEvent = { kind: "node_changed"; node_uuids: string[]; parent_uuids: string[] } | { kind: "node_deleted"; node_uuids: string[]; parent_uuids: string[] } | { kind: "graph_changed"; node_uuids: string[] } | { kind: "history_changed" } | { kind: "settings_changed" } | { kind: "sync_status_changed" } | { kind: "workspace_changed" };

export type DomainEventMessage = DomainEvent;

export type Edge = {
	src: number,
	dst: number,
	kind: string,
	weight: number | null,
	created_at: number,
};

export type GraphSnapshot = {
	nodes: Node[],
	edges: Edge[],
};

export type MobileSystemInfo = {
	deviceName: string,
	safeArea: SafeAreaInsets,
};

export type Node = {
	id: number,
	uuid: string,
	kind: NodeKind,
	title: string | null,
	content: string,
	content_json: string | null,
	parent_id: number | null,
	position: number | null,
	created_at: number,
	updated_at: number,
};

/**  Closed set of node shapes understood by storage, sync and the UI. */
export type NodeKind = "page" | "block" | "tag" | "entity" | "attachment";

export type SafeAreaInsets = {
	top: number | null,
	right: number | null,
	bottom: number | null,
	left: number | null,
};

export type SearchHit = {
	node: Node,
	score: number | null,
};

export type SecretKey = "SYNC_TOKEN";

export type SettingsSnapshot = {
	windowDecorationMode: WindowDecorationMode,
	syncDirectory: string | null,
	syncServerUrl: string | null,
	configuredKeys: SecretKey[],
	configPath: string,
};

export type SettingsUpdate = {
	windowDecorationMode: WindowDecorationMode,
	syncDirectory: string | null,
	syncServerUrl: string | null,
	apiKeys?: Partial<{ [key in SecretKey]: string }>,
	clearKeys?: SecretKey[],
};

export type StartupStatus = { state: "starting"; message: string } | { state: "ready" } | { state: "error"; message: string };

export type SyncConnectionState = "disabled" | "connecting" | "syncing" | "online" | "offline" | "error";

export type SyncStatus = {
	state: SyncConnectionState,
	serverUrl: string | null,
	lastServerSeq: number,
	pendingOperations: number,
	message: string | null,
};

export type WindowDecorationMode = "native" | "borderless";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

