/* eslint-disable */
// Generated by tauri-specta. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	isReady: () => __TAURI_INVOKE<boolean>("is_ready"),
	startupStatus: () => __TAURI_INVOKE<StartupStatus>("startup_status"),
	loadSettings: () => __TAURI_INVOKE<SettingsSnapshot>("load_settings"),
	saveSettings: (update: SettingsUpdate) => __TAURI_INVOKE<SettingsSnapshot>("save_settings", { update }),
	testCompletionProvider: (request: ProviderProbeRequest) => __TAURI_INVOKE<ProviderProbeResult>("test_completion_provider", { request }),
	restartApp: () => __TAURI_INVOKE<void>("restart_app"),
	backgroundStatus: () => __TAURI_INVOKE<BackgroundStatus>("background_status"),
	setBackgroundPaused: (paused: boolean) => __TAURI_INVOKE<void>("set_background_paused", { paused }),
	retryBackgroundJobs: () => __TAURI_INVOKE<null>("retry_background_jobs"),
	clearBackgroundJobs: () => __TAURI_INVOKE<null>("clear_background_jobs"),
	historyStatus: () => __TAURI_INVOKE<[number, number]>("history_status"),
	undo: () => __TAURI_INVOKE<boolean>("undo"),
	redo: () => __TAURI_INVOKE<boolean>("redo"),
	createNode: (kind: NodeKind, title: string | null, content: string, contentJson: string | null) => __TAURI_INVOKE<Node>("create_node", { kind, title, content, contentJson }),
	updateNode: (id: number, title: string | null, content: string, contentJson: string | null) => __TAURI_INVOKE<null>("update_node", { id, title, content, contentJson }),
	updateBlockWithRefs: (id: number, block: BlockContent) => __TAURI_INVOKE<[Node, number]>("update_block_with_refs", { id, block }),
	splitBlock: (id: number, parts: BlockContent[]) => __TAURI_INVOKE<Node[]>("split_block", { id, parts }),
	linkNodes: (src: number, dst: number, kind: string, weight: number | null) => __TAURI_INVOKE<null>("link_nodes", { src, dst, kind, weight }),
	getNode: (id: number) => __TAURI_INVOKE<{
	id: number,
	uuid: string,
	kind: NodeKind,
	title: string | null,
	content: string,
	content_json: string | null,
	parent_id: number | null,
	position: number | null,
	created_at: number,
	updated_at: number,
} | null>("get_node", { id }),
	getContainingPage: (id: number) => __TAURI_INVOKE<{
	id: number,
	uuid: string,
	kind: NodeKind,
	title: string | null,
	content: string,
	content_json: string | null,
	parent_id: number | null,
	position: number | null,
	created_at: number,
	updated_at: number,
} | null>("get_containing_page", { id }),
	neighbors: (id: number, depth: number) => __TAURI_INVOKE<Node[]>("neighbors", { id, depth }),
	searchFts: (query: string, limit: number) => __TAURI_INVOKE<SearchHit[]>("search_fts", { query, limit }),
	searchVec: (query: string, limit: number) => __TAURI_INVOKE<SearchHit[]>("search_vec", { query, limit }),
	searchHybrid: (query: string, limit: number) => __TAURI_INVOKE<SearchHit[]>("search_hybrid", { query, limit }),
	/**  Retrieve via hybrid RRF, then rerank with the configured provider. */
	searchAgentic: (query: string, limit: number) => __TAURI_INVOKE<SearchHit[]>("search_agentic", { query, limit }),
	rerank: (query: string, documents: string[]) => __TAURI_INVOKE<([number, number | null])[]>("rerank", { query, documents }),
	chat: (message: string) => __TAURI_INVOKE<string>("chat", { message }),
	chatStream: (history: ChatTurn[], message: string, allowWrites: boolean, activeNodeId: number | null, requestId: string, onEvent: Channel<ChatEvent>) => __TAURI_INVOKE<string>("chat_stream", { history, message, allowWrites, activeNodeId, requestId, onEvent }),
	cancelChat: (requestId: string) => __TAURI_INVOKE<boolean>("cancel_chat", { requestId }),
	listEntities: (limit: number | null) => __TAURI_INVOKE<Node[]>("list_entities", { limit }),
	listPages: (limit: number | null) => __TAURI_INVOKE<Node[]>("list_pages", { limit }),
	deletePage: (id: number) => __TAURI_INVOKE<boolean>("delete_page", { id }),
	findBacklinks: (id: number, kind: string | null) => __TAURI_INVOKE<Node[]>("find_backlinks", { id, kind }),
	graphSnapshot: (focusId: number | null) => __TAURI_INVOKE<GraphSnapshot>("graph_snapshot", { focusId }),
	exportData: () => __TAURI_INVOKE<string | null>("export_data"),
	importData: () => __TAURI_INVOKE<string | null>("import_data"),
	createBackup: () => __TAURI_INVOKE<string>("create_backup"),
	chooseSyncDirectory: () => __TAURI_INVOKE<string | null>("choose_sync_directory"),
	syncPush: () => __TAURI_INVOKE<string>("sync_push"),
	syncPull: () => __TAURI_INVOKE<string>("sync_pull"),
	attachFile: (parentId: number) => __TAURI_INVOKE<{
	id: number,
	uuid: string,
	kind: NodeKind,
	title: string | null,
	content: string,
	content_json: string | null,
	parent_id: number | null,
	position: number | null,
	created_at: number,
	updated_at: number,
} | null>("attach_file", { parentId }),
	listAttachments: (parentId: number) => __TAURI_INVOKE<Node[]>("list_attachments", { parentId }),
	openAttachment: (id: number) => __TAURI_INVOKE<null>("open_attachment", { id }),
	deleteAttachment: (id: number) => __TAURI_INVOKE<boolean>("delete_attachment", { id }),
	createPage: (title: string) => __TAURI_INVOKE<Node>("create_page", { title }),
	listBlockChildren: (parentId: number) => __TAURI_INVOKE<Node[]>("list_block_children", { parentId }),
	createBlock: (parentId: number | null, position: number | null, content: string, contentJson: string | null) => __TAURI_INVOKE<Node>("create_block", { parentId, position, content, contentJson }),
	moveBlock: (id: number, newParentId: number | null, newPosition: number | null) => __TAURI_INVOKE<Node>("move_block", { id, newParentId, newPosition }),
	reorderBlock: (id: number, direction: ReorderDirection) => __TAURI_INVOKE<Node>("reorder_block", { id, direction }),
	deleteBlock: (id: number) => __TAURI_INVOKE<boolean>("delete_block", { id }),
	replaceBlockRefs: (blockId: number, wikilinkTitles: string[], blockUuids: string[]) => __TAURI_INVOKE<number>("replace_block_refs", { blockId, wikilinkTitles, blockUuids }),
	getOrCreatePageByTitle: (title: string) => __TAURI_INVOKE<Node>("get_or_create_page_by_title", { title }),
	getPageByTitle: (title: string) => __TAURI_INVOKE<{
	id: number,
	uuid: string,
	kind: NodeKind,
	title: string | null,
	content: string,
	content_json: string | null,
	parent_id: number | null,
	position: number | null,
	created_at: number,
	updated_at: number,
} | null>("get_page_by_title", { title }),
	getNodeByUuid: (uuid: string) => __TAURI_INVOKE<{
	id: number,
	uuid: string,
	kind: NodeKind,
	title: string | null,
	content: string,
	content_json: string | null,
	parent_id: number | null,
	position: number | null,
	created_at: number,
	updated_at: number,
} | null>("get_node_by_uuid", { uuid }),
	searchPagesByTitle: (query: string, limit: number) => __TAURI_INVOKE<Node[]>("search_pages_by_title", { query, limit }),
	searchBlocksFts: (query: string, limit: number) => __TAURI_INVOKE<Node[]>("search_blocks_fts", { query, limit }),
};

/** Events */
export const events = {
	domainEvent: makeEvent<DomainEventMessage>("domain:event"),
};

/* Types */
export type BackgroundFailure = {
	queue: BackgroundQueue,
	nodeId: number,
	nodeTitle: string | null,
	retryCount: number,
	lastAttempt: number | null,
	failureKind: FailureKind,
	lastError: string,
	terminal: boolean,
};

export type BackgroundQueue = "embedding" | "extraction";

export type BackgroundStatus = {
	paused: boolean,
	embeddingsPending: number,
	embeddingsFailed: number,
	extractionsPending: number,
	extractionsFailed: number,
	failures: BackgroundFailure[],
};

export type BlockContent = {
	content: string,
	wikilinkTitles: string[],
	blockUuids: string[],
};

export type CapabilityProbeResult = {
	name: string,
	ok: boolean,
	latencyMs: number,
	detail: string,
};

export type ChatEvent = { kind: "text_delta"; text: string } | { kind: "reasoning"; text: string } | { kind: "tool_start"; id: string; name: string; args: unknown } | { kind: "tool_end"; id: string; result: string } | { kind: "done"; text: string } | { kind: "error"; message: string } | { kind: "usage"; inputTokens: number; outputTokens: number; totalTokens: number } | { kind: "cancelled" };

export type ChatTurn = { role: "user"; text: string } | { role: "assistant"; text: string };

export type CompletionProtocol = "openai" | "anthropic";

/**
 *  The single frontend invalidation stream for persisted Rust state.
 *  Payloads carry affected IDs when a command can identify them; whole-workspace
 *  replacements (import/sync) deliberately request a full cache refresh.
 */
export type DomainEvent = { kind: "node_changed"; node_ids: number[]; parent_ids: number[] } | { kind: "node_deleted"; node_ids: number[]; parent_ids: number[] } | { kind: "graph_changed"; node_ids: number[] } | { kind: "history_changed" } | { kind: "background_status_changed" } | { kind: "settings_changed" } | { kind: "workspace_changed" };

export type DomainEventMessage = DomainEvent;

export type Edge = {
	src: number,
	dst: number,
	kind: string,
	weight: number | null,
	created_at: number,
};

export type EmbeddingProvider = "openrouter" | "openai" | "cohere" | "voyageai" | "gemini" | "local";

export type ExtractionProtocol = "inherit" | "openai" | "anthropic";

export type FailureKind = "unknown" | "transient" | "auth" | "provider_request" | "schema" | "configuration" | "network" | "provider_response" | "apply";

export type GraphSnapshot = {
	nodes: Node[],
	edges: Edge[],
};

export type Node = {
	id: number,
	uuid: string,
	kind: NodeKind,
	title: string | null,
	content: string,
	content_json: string | null,
	parent_id: number | null,
	position: number | null,
	created_at: number,
	updated_at: number,
};

/**  Closed set of node shapes understood by storage, sync and the UI. */
export type NodeKind = "page" | "block" | "tag" | "entity" | "attachment";

export type ProviderKeyScope = "chat" | "extraction";

export type ProviderProbeRequest = {
	protocol: CompletionProtocol,
	baseUrl: string,
	model: string,
	apiKey: string | null,
	keyScope: ProviderKeyScope | null,
};

export type ProviderProbeResult = {
	capabilities: CapabilityProbeResult[],
};

export type ReorderDirection = "up" | "down";

export type RerankProvider = "openrouter" | "local";

export type SearchHit = {
	node: Node,
	score: number | null,
};

export type SettingsSnapshot = {
	localOnly: boolean,
	entityExtractionEnabled: boolean,
	queryRewritingEnabled: boolean,
	chatModel: string,
	chatProtocol: CompletionProtocol,
	chatBaseUrl: string,
	extractionModel: string,
	extractionProtocol: ExtractionProtocol,
	extractionBaseUrl: string,
	embeddingProvider: EmbeddingProvider,
	embeddingModel: string,
	embeddingNdims: string,
	rerankProvider: RerankProvider,
	rerankModel: string,
	openrouterBaseUrl: string,
	openaiBaseUrl: string,
	windowDecorationMode: WindowDecorationMode,
	syncDirectory: string,
	kdeDecorationsAvailable: boolean,
	configuredKeys: string[],
	localModelsAvailable: boolean,
	configPath: string,
};

export type SettingsUpdate = {
	localOnly: boolean,
	entityExtractionEnabled: boolean,
	queryRewritingEnabled: boolean,
	chatModel: string,
	chatProtocol: CompletionProtocol,
	chatBaseUrl: string,
	extractionModel: string,
	extractionProtocol: ExtractionProtocol,
	extractionBaseUrl: string,
	embeddingProvider: EmbeddingProvider,
	embeddingModel: string,
	embeddingNdims: string,
	rerankProvider: RerankProvider,
	rerankModel: string,
	openrouterBaseUrl: string,
	openaiBaseUrl: string,
	windowDecorationMode: WindowDecorationMode,
	syncDirectory: string,
	apiKeys?: { [key in string]: string },
	clearKeys?: string[],
};

export type StartupStatus = { state: "starting"; message: string } | { state: "ready" } | { state: "error"; message: string };

export type WindowDecorationMode = "native" | "borderless" | "kde";

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

