#[cfg(target_os = "android")]
mod android_tls;
mod attachment_protocol;
mod commands;
mod settings;
mod sync;

use notes_core::db;
use std::sync::{Arc, RwLock};
use tauri::Manager;
use tauri_specta::Event;

fn specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            commands::is_ready,
            commands::startup_status,
            commands::mobile_system_info,
            commands::set_system_bars_style,
            commands::sync_status,
            commands::server_ai_status,
            commands::save_server_ai_settings,
            commands::save_server_ai_provider,
            commands::probe_server_ai_provider,
            commands::reindex_server_ai,
            commands::load_settings,
            commands::save_settings,
            commands::reset_settings,
            commands::retry_sync,
            commands::restart_app,
            commands::history_status,
            commands::undo,
            commands::redo,
            commands::rename_page,
            commands::set_page_layout,
            commands::create_note,
            commands::ensure_journal,
            commands::get_journal,
            commands::list_journals,
            commands::append_to_journal,
            commands::get_page,
            commands::get_page_document,
            commands::get_page_render_snapshot,
            commands::replace_page_document,
            commands::get_block,
            commands::set_block_content,
            commands::set_block_style,
            commands::set_task_state,
            commands::split_block,
            commands::get_containing_page,
            commands::neighbors,
            commands::search_notes,
            commands::chat_stream,
            commands::cancel_chat,
            commands::list_pages,
            commands::delete_page,
            commands::find_backlinks,
            commands::graph_snapshot,
            commands::export_data,
            commands::import_data,
            commands::logseq_import_capability,
            commands::prepare_logseq_import,
            commands::logseq_import_diagnostics,
            commands::commit_logseq_import,
            commands::discard_logseq_import,
            commands::create_backup,
            commands::attach_file,
            commands::list_attachments,
            commands::resolve_attachment_images,
            commands::open_attachment,
            commands::delete_attachment,
            commands::create_page,
            commands::list_block_children,
            commands::create_block,
            commands::indent_block,
            commands::outdent_block,
            commands::move_block_up,
            commands::move_block_down,
            commands::delete_block,
            commands::get_or_create_page_by_title,
            commands::get_page_by_title,
            commands::search_pages_by_title,
            commands::search_blocks_fts,
        ])
        .events(tauri_specta::collect_events![
            commands::DomainEventMessage,
            commands::StartupReadyEvent,
            commands::StartupErrorEvent
        ])
        // The UI contract intentionally uses JavaScript numbers. Every exposed 64-bit value is
        // bounded below Number.MAX_SAFE_INTEGER: Unix-second timestamps, attachment sizes capped
        // at 100 MiB, SQLite row counts, and server queue counters. HLCs and server sequences are
        // synchronization internals and never cross the Tauri command/event boundary.
        .dangerously_cast_bigints_to_number()
}

pub fn export_bindings(path: impl AsRef<std::path::Path>) -> Result<(), String> {
    specta_builder()
        .export(
            specta_typescript::Typescript::default()
                .header("/* eslint-disable */\n// Generated by tauri-specta. Do not edit.\n"),
            path,
        )
        .map_err(|error| error.to_string())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    init_tracing();

    let specta_builder = specta_builder();

    #[cfg(all(debug_assertions, not(mobile)))]
    export_bindings("../src/lib/bindings.ts").expect("exporting TypeScript bindings");

    let invoke_handler = specta_builder.invoke_handler();
    let context = tauri::generate_context!();
    #[cfg(not(mobile))]
    let (context, main_window_config) = {
        let mut context = context;
        let config = context
            .config_mut()
            .app
            .windows
            .iter_mut()
            .find(|window| window.label == "main")
            .expect("main window configuration");
        let main_window_config = config.clone();
        config.create = false;
        (context, main_window_config)
    };
    let builder = tauri::Builder::default()
        .register_asynchronous_uri_scheme_protocol(
            attachment_protocol::ATTACHMENT_PROTOCOL,
            attachment_protocol::protocol,
        )
        .plugin(tauri_plugin_opener::init());

    #[cfg(not(target_os = "android"))]
    let builder = builder.plugin(tauri_plugin_dialog::init());

    #[cfg(target_os = "android")]
    let builder = builder
        .plugin(tauri_plugin_android_fs::init())
        .plugin(tauri_plugin_mobile_system::init());

    // Development-only bridge for MCP-powered UI inspection and automation.
    // Restrict it to localhost; release builds do not register the plugin. Reachable on Android
    // over `adb forward tcp:9223 tcp:9223`, same as desktop; not yet enabled on iOS (untested).
    #[cfg(all(debug_assertions, not(target_os = "ios")))]
    let builder = builder.plugin(
        tauri_plugin_mcp_bridge::Builder::new()
            .bind_address("127.0.0.1")
            .build(),
    );

    builder
        .setup(move |app| {
            #[cfg(not(mobile))]
            settings::create_main_window(app, &main_window_config)?;
            specta_builder.mount_events(app);
            let handle = app.handle().clone();
            let data_dir = app.path().app_data_dir().expect("resolving app data dir");
            std::fs::create_dir_all(&data_dir).expect("creating data dir");
            let blob_store = notes_blob::BlobStore::new(data_dir.clone());
            // v2: previews switched from lossless to lossy WebP; the old
            // lossless blobs would never be referenced again, so drop the dir.
            let image_cache = notes_blob::BlobStore::new(data_dir.join("image-cache-v2"));
            let stale_image_cache = data_dir.join("image-cache-v1");
            std::thread::spawn(move || {
                let _ = std::fs::remove_dir_all(stale_image_cache);
            });
            app.manage(commands::LogseqImportSessions::default());

            let startup = Arc::new(RwLock::new(commands::StartupStatus::Starting {
                message: "Loading device settings…".into(),
            }));
            handle.manage(commands::Startup {
                status: startup.clone(),
            });
            let sync_runtime = sync::SyncRuntime::disabled();
            let sync_status = sync_runtime.status.clone();
            let sync_retries = sync_runtime.subscribe_retries();
            app.manage(sync_runtime);

            let db_path = data_dir.join("notes.db");
            let configured_settings = match settings::runtime(&handle) {
                Ok(settings) => settings,
                Err(error) => {
                    report_startup_error(&handle, &startup, error);
                    return Ok(());
                }
            };
            let sync_credentials = match configured_settings.sync_credentials() {
                Ok(credentials) => credentials,
                Err(error) => {
                    report_startup_error(&handle, &startup, error);
                    return Ok(());
                }
            };
            let remote_ai = sync_credentials
                .as_ref()
                .map(|(server_url, token)| {
                    notes_sync::HttpTransport::new(server_url.clone(), token.clone())
                })
                .transpose();
            let remote_ai = match remote_ai {
                Ok(remote) => remote,
                Err(error) => {
                    report_startup_error(&handle, &startup, error);
                    return Ok(());
                }
            };
            *startup.write().unwrap_or_else(|error| error.into_inner()) =
                commands::StartupStatus::Starting {
                    message: "Opening local notes database…".into(),
                };

            tauri::async_runtime::spawn(async move {
                match db::open(&db_path).await {
                    Ok(conn) => {
                        handle.manage(commands::AppState {
                            conn: conn.clone(),
                            blob_store: blob_store.clone(),
                            image_cache,
                            preview_jobs: Arc::new(attachment_protocol::PreviewJobs::default()),
                            remote_ai,
                            chat_cancellations: Arc::new(std::sync::Mutex::new(
                                std::collections::HashMap::new(),
                            )),
                        });
                        if let Some((server_url, token)) = sync_credentials {
                            sync::spawn_worker(
                                handle.clone(),
                                conn.clone(),
                                server_url,
                                token,
                                blob_store,
                                sync_status,
                                sync_retries,
                            )
                        }
                        *startup.write().unwrap_or_else(|e| e.into_inner()) =
                            commands::StartupStatus::Ready;
                        let _ = commands::StartupReadyEvent.emit(&handle);
                        tracing::info!(?db_path, "notes-rs ready");
                    }
                    Err(error) => {
                        let message = format!("{error:#}");
                        tracing::error!(%message, "notes-rs startup failed");
                        *startup.write().unwrap_or_else(|e| e.into_inner()) =
                            commands::StartupStatus::Error {
                                message: message.clone(),
                            };
                        let _ = commands::StartupErrorEvent { message }.emit(&handle);
                    }
                }
            });

            Ok(())
        })
        .invoke_handler(invoke_handler)
        .run(context)
        .expect("error while running tauri application");
}

fn report_startup_error(
    handle: &tauri::AppHandle,
    startup: &Arc<RwLock<commands::StartupStatus>>,
    error: anyhow::Error,
) {
    let message = format!("{error:#}");
    tracing::error!(%message, "notes-rs startup failed");
    *startup.write().unwrap_or_else(|error| error.into_inner()) = commands::StartupStatus::Error {
        message: message.clone(),
    };
    let _ = commands::StartupErrorEvent { message }.emit(handle);
}

#[cfg(not(target_os = "android"))]
fn init_tracing() {
    tracing_subscriber::fmt()
        .with_max_level(tracing::Level::INFO)
        .init();
}

#[cfg(target_os = "android")]
fn init_tracing() {
    use tracing_logcat::{LogcatMakeWriter, LogcatTag};

    let writer = LogcatMakeWriter::new(LogcatTag::Fixed("notes-rs".into()))
        .expect("creating Android logcat writer");
    tracing_subscriber::fmt()
        .with_ansi(false)
        .with_target(true)
        .with_max_level(tracing::Level::INFO)
        .with_writer(writer)
        .init();
}
