mod commands;
mod settings;
mod sync;

use notes_core::db;
use std::sync::{Arc, RwLock};
use tauri::{Emitter, Manager};

fn specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            commands::is_ready,
            commands::startup_status,
            commands::mobile_system_info,
            commands::set_system_bars_style,
            commands::sync_status,
            commands::server_ai_status,
            commands::save_server_ai_settings,
            commands::reindex_server_ai,
            commands::load_settings,
            commands::save_settings,
            commands::reset_settings,
            commands::restart_app,
            commands::history_status,
            commands::undo,
            commands::redo,
            commands::create_node,
            commands::update_node,
            commands::rename_page,
            commands::create_note,
            commands::set_block_content,
            commands::split_block,
            commands::link_nodes,
            commands::get_node,
            commands::get_containing_page,
            commands::neighbors,
            commands::search_fts,
            commands::search_vec,
            commands::search_hybrid,
            commands::search_agentic,
            commands::chat_stream,
            commands::cancel_chat,
            commands::list_entities,
            commands::list_pages,
            commands::delete_page,
            commands::find_backlinks,
            commands::graph_snapshot,
            commands::export_data,
            commands::import_data,
            commands::create_backup,
            commands::choose_sync_directory,
            commands::sync_push,
            commands::sync_pull,
            commands::attach_file,
            commands::list_attachments,
            commands::open_attachment,
            commands::delete_attachment,
            commands::create_page,
            commands::list_block_children,
            commands::create_block,
            commands::indent_block,
            commands::outdent_block,
            commands::move_block_up,
            commands::move_block_down,
            commands::delete_block,
            commands::get_or_create_page_by_title,
            commands::get_page_by_title,
            commands::get_node_by_uuid,
            commands::search_pages_by_title,
            commands::search_blocks_fts,
        ])
        .events(tauri_specta::collect_events![commands::DomainEventMessage])
        .dangerously_cast_bigints_to_number()
}

pub fn export_bindings(path: impl AsRef<std::path::Path>) -> Result<(), String> {
    specta_builder()
        .export(
            specta_typescript::Typescript::default()
                .header("/* eslint-disable */\n// Generated by tauri-specta. Do not edit.\n"),
            path,
        )
        .map_err(|error| error.to_string())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    init_tracing();

    let specta_builder = specta_builder();

    #[cfg(debug_assertions)]
    export_bindings("../src/lib/bindings.ts").expect("exporting TypeScript bindings");

    let invoke_handler = specta_builder.invoke_handler();
    let builder = tauri::Builder::default().plugin(tauri_plugin_opener::init());

    #[cfg(not(target_os = "android"))]
    let builder = builder.plugin(tauri_plugin_dialog::init());

    #[cfg(target_os = "android")]
    let builder = builder
        .plugin(tauri_plugin_android_fs::init())
        .plugin(tauri_plugin_mobile_system::init());

    // Development-only bridge for MCP-powered UI inspection and automation.
    // Restrict it to localhost; release builds do not register the plugin.
    #[cfg(all(debug_assertions, not(mobile)))]
    let builder = builder.plugin(
        tauri_plugin_mcp_bridge::Builder::new()
            .bind_address("127.0.0.1")
            .build(),
    );

    builder
        .setup(move |app| {
            specta_builder.mount_events(app);
            let handle = app.handle().clone();
            let data_dir = app.path().app_data_dir().expect("resolving app data dir");
            std::fs::create_dir_all(&data_dir).expect("creating data dir");

            let startup = Arc::new(RwLock::new(commands::StartupStatus::Starting {
                message: "Loading device settings…".into(),
            }));
            handle.manage(commands::Startup {
                status: startup.clone(),
            });
            let sync_runtime = sync::SyncRuntime::disabled();
            let sync_status = sync_runtime.status.clone();
            app.manage(sync_runtime);

            #[cfg(not(mobile))]
            if let Err(error) = settings::apply_saved_window_preferences(&handle) {
                tracing::warn!(%error, "failed to apply saved window preferences");
            }

            let db_path = data_dir.join("notes.db");
            let configured_settings = match settings::runtime(&handle) {
                Ok(settings) => settings,
                Err(error) => {
                    report_startup_error(&handle, &startup, error);
                    return Ok(());
                }
            };
            let sync_credentials = match configured_settings.sync_credentials() {
                Ok(credentials) => credentials,
                Err(error) => {
                    report_startup_error(&handle, &startup, error);
                    return Ok(());
                }
            };
            let remote_ai = sync_credentials
                .as_ref()
                .map(|(server_url, token)| {
                    notes_sync::HttpTransport::new(server_url.clone(), token.clone())
                })
                .transpose();
            let remote_ai = match remote_ai {
                Ok(remote) => remote,
                Err(error) => {
                    report_startup_error(&handle, &startup, error);
                    return Ok(());
                }
            };
            *startup.write().unwrap_or_else(|error| error.into_inner()) =
                commands::StartupStatus::Starting {
                    message: "Opening local notes database…".into(),
                };

            tauri::async_runtime::spawn(async move {
                match db::open(&db_path).await {
                    Ok(conn) => {
                        handle.manage(commands::AppState {
                            conn: conn.clone(),
                            remote_ai,
                            chat_cancellations: Arc::new(std::sync::Mutex::new(
                                std::collections::HashMap::new(),
                            )),
                        });
                        if let Some((server_url, token)) = sync_credentials {
                            sync::spawn_worker(
                                handle.clone(),
                                conn.clone(),
                                server_url,
                                token,
                                data_dir.clone(),
                                sync_status,
                            )
                        }
                        *startup.write().unwrap_or_else(|e| e.into_inner()) =
                            commands::StartupStatus::Ready;
                        let _ = handle.emit("app:ready", ());
                        tracing::info!(?db_path, "notes-rs ready");
                    }
                    Err(error) => {
                        let message = format!("{error:#}");
                        tracing::error!(%message, "notes-rs startup failed");
                        *startup.write().unwrap_or_else(|e| e.into_inner()) =
                            commands::StartupStatus::Error {
                                message: message.clone(),
                            };
                        let _ = handle.emit("app:startup-error", message);
                    }
                }
            });

            Ok(())
        })
        .invoke_handler(invoke_handler)
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

fn report_startup_error(
    handle: &tauri::AppHandle,
    startup: &Arc<RwLock<commands::StartupStatus>>,
    error: anyhow::Error,
) {
    let message = format!("{error:#}");
    tracing::error!(%message, "notes-rs startup failed");
    *startup.write().unwrap_or_else(|error| error.into_inner()) = commands::StartupStatus::Error {
        message: message.clone(),
    };
    let _ = handle.emit("app:startup-error", message);
}

#[cfg(not(target_os = "android"))]
fn init_tracing() {
    tracing_subscriber::fmt()
        .with_max_level(tracing::Level::INFO)
        .init();
}

#[cfg(target_os = "android")]
fn init_tracing() {
    use tracing_logcat::{LogcatMakeWriter, LogcatTag};

    let writer = LogcatMakeWriter::new(LogcatTag::Fixed("notes-rs".into()))
        .expect("creating Android logcat writer");
    tracing_subscriber::fmt()
        .with_ansi(false)
        .with_target(true)
        .with_max_level(tracing::Level::INFO)
        .with_writer(writer)
        .init();
}
